# This is a basic workflow to help you get started with Actions

name: "Newman Tests"
on: [push, pull_request]

jobs:
  build:
    runs-ppm: ubuntu-latest
    container:
      image: postman/newman
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: run API Tests
        run: newman run "Restful Booker BVT Copy.postman_collection.json" -e "Production Copy.postman"
